// Catalog loader. Data lives in catalog.data.json, generated by gen-catalog.mjs
// from the repo's reverse-engineered assets (corpus examples = verified-live, OG
// registry = bundle-derived, marketplace assets = live-schema). Re-run the
// generator when the bundle rotates or a new example is harvested.
//
// Interface (stable — the compiler depends on it):
//   catalog.step(type)    -> { type, confidence, situational[], premium,
//                              isMultipathContainer, usesCustomInputs, requiredFields[], ... } | undefined
//   catalog.trigger(type) -> { type, masterType, category, confidence, ... } | undefined
//   catalog.filterModel(triggerType) -> recovered filter-row schema | undefined
//   catalog.stepCapabilities() -> universal author/edit capabilities for all steps
//   catalog.allSteps() / catalog.allTriggers() -> type[]  (for coverage reporting)
import CATALOG_DATA from './catalog.data.json' with { type: 'json' };
import { CATALOG_CORRECTIONS, REQUIRED_FIELDS } from './required-fields.mjs';

function data() {
  return CATALOG_DATA;
}

// Overlay the hand-maintained corrections onto the generated entries. catalog.data.json is
// regenerated wholesale by gen-catalog.mjs (which lives in the ghl-workflow-api-docs repo),
// so a correction hand-written INTO it would be lost on the next regen — it has to be
// applied here instead. See required-fields.mjs for the evidence behind each one.
//
// `attestedRequiredFields` is deliberately a SEPARATE key from the generated
// `requiredFields`: the generated one is marketplace-schema derived and does not describe
// the emitted shape (goto declares "placement", which the engine has never emitted), so it
// stays advisory. Only the attested set is enforced.
export function correctSteps(steps) {
  const out = { ...steps };
  for (const [type, fix] of Object.entries(CATALOG_CORRECTIONS)) {
    const { reason, ...patch } = fix;
    out[type] = { ...(out[type] ?? { type, kind: 'step' }), ...patch };
  }
  for (const [type, spec] of Object.entries(REQUIRED_FIELDS)) {
    if (!out[type]) continue;
    out[type] = { ...out[type], attestedRequiredFields: Object.keys(spec.fields) };
  }
  return out;
}

// Map a trigger type to its recovered filter model. The generator keys filter
// models by class name (BirthdayReminderFilter), not slug — resolve by scanning
// the source_path / class for the trigger slug.
function findFilterModel(d, triggerType) {
  const models = d.filterModels ?? {};
  for (const [cls, m] of Object.entries(models)) {
    const path = (m.source_path ?? '').toLowerCase();
    const rows = m.filter_rows ?? [];
    // heuristic: match on a filter value that embeds the trigger's domain, or class name
    if (rows.some((r) => (r.value ?? '').includes(triggerType))) return { class: cls, ...m };
  }
  return undefined;
}

export function loadCatalog() {
  const d = data();
  const steps = correctSteps(d.steps);
  return {
    step: (type) => steps[type],
    trigger: (type) => d.triggers[type],
    filterModel: (type) => findFilterModel(d, type),
    stepCapabilities: () => d.stepCapabilities ?? {},
    allSteps: () => Object.keys(steps),
    allTriggers: () => Object.keys(d.triggers),
    // coverage snapshot for reporting / tests
    counts: () => ({
      steps: d.stepCount, triggers: d.triggerCount,
      verifiedLiveSteps: Object.values(steps).filter((s) => s.confidence === 'verified-live').length,
    }),
  };
}
