// Catalog loader. Data lives in catalog.data.json, generated by gen-catalog.mjs
// from the repo's reverse-engineered assets (corpus examples = verified-live, OG
// registry = bundle-derived, marketplace assets = live-schema). Re-run the
// generator when the bundle rotates or a new example is harvested.
//
// Interface (stable — the compiler depends on it):
//   catalog.step(type)    -> { type, confidence, situational[], premium,
//                              isMultipathContainer, usesCustomInputs, requiredFields[], ... } | undefined
//   catalog.trigger(type) -> { type, masterType, category, confidence, ... } | undefined
//   catalog.filterModel(triggerType) -> recovered filter-row schema | undefined
//   catalog.allSteps() / catalog.allTriggers() -> type[]  (for coverage reporting)
import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';

const HERE = dirname(fileURLToPath(import.meta.url));
let DATA;
function data() {
  if (!DATA) DATA = JSON.parse(readFileSync(resolve(HERE, 'catalog.data.json'), 'utf8'));
  return DATA;
}

// Map a trigger type to its recovered filter model. The generator keys filter
// models by class name (BirthdayReminderFilter), not slug — resolve by scanning
// the source_path / class for the trigger slug.
function findFilterModel(d, triggerType) {
  const models = d.filterModels ?? {};
  for (const [cls, m] of Object.entries(models)) {
    const path = (m.source_path ?? '').toLowerCase();
    const rows = m.filter_rows ?? [];
    // heuristic: match on a filter value that embeds the trigger's domain, or class name
    if (rows.some((r) => (r.value ?? '').includes(triggerType))) return { class: cls, ...m };
  }
  return undefined;
}

export function loadCatalog() {
  const d = data();
  return {
    step: (type) => d.steps[type],
    trigger: (type) => d.triggers[type],
    filterModel: (type) => findFilterModel(d, type),
    allSteps: () => Object.keys(d.steps),
    allTriggers: () => Object.keys(d.triggers),
    // coverage snapshot for reporting / tests
    counts: () => ({
      steps: d.stepCount, triggers: d.triggerCount,
      verifiedLiveSteps: Object.values(d.steps).filter((s) => s.confidence === 'verified-live').length,
    }),
  };
}
