// Attested required-field enforcement, plus corrections to the generated catalog.
//
// WHY THIS IS NOT IN catalog.data.json
// ------------------------------------
// That file is GENERATED by gen-catalog.mjs, which lives in the ghl-workflow-api-docs
// repo and rewrites it wholesale (`writeFileSync(... JSON.stringify(data))`). A hand-edit
// there is silently lost the next time anyone regenerates and copies it across. This
// overlay is hand-maintained, lives only in the plugin, and is applied on top by
// catalog.mjs — so a regeneration cannot drop it. `catalog-corrections.test.mjs` asserts
// each correction is still NEEDED, so an entry cannot go stale unnoticed.
//
// WHY NOT DRIVE OFF THE CATALOG'S OWN `requiredFields`
// ----------------------------------------------------
// It is marketplace-SCHEMA derived and does not describe the shape GHL actually emits.
// `goto` declares ["placement","targetNodeId"], but its verified-live example carries
// only {targetNodeId, type} and the engine has never emitted `placement`. Enforcing the
// declared set would reject every goto ever built. So the generated field stays advisory
// (query-catalog prints it), and ONLY the entries below — each attested against a
// committed capture or an observed builder error — are enforced.
//
// EVIDENCE: research/ai-agents-internal/flow-builder-required-fields.md, live on AU
// wdzEoUZnXO9tB3PPzcot 2026-07-25/26. Nine conversationai_* node types were built with
// deliberately minimal attributes; the builder reported "Resolve 7 Errors" while the
// engine reported `verify: { pass: 14, issues: [] }`. Supplying the fields below took it
// to "Resolve 1 Errors", and the survivor was conversationai_end — because its DOCUMENTED
// KEY NAMES WERE WRONG (see CATALOG_CORRECTIONS).
import { IRError } from './ir.mjs';

// Corrections applied over the generated catalog entry, merged in catalog.mjs.
// `reason` is required — an unexplained correction is indistinguishable from a typo.
export const CATALOG_CORRECTIONS = {
  // 🔴 The generated keys for this node are WRONG. Authoring the documented
  // `reactivate: false` was accepted, persisted as an unknown key, and left the
  // actually-required `sleepEnabled` unset — so the node kept its error badge. The shape
  // below was captured verbatim by filling the node in the builder, clicking Save action
  // then Save workflow, and exporting. Promoted to verified-live on that capture, which
  // also switches on the ATTR_KEY guard (it only fires on verified-live types) so an
  // invented key can no longer pass through here.
  conversationai_end: {
    reason: 'documented keys customMessage/reactivate/duration are wrong; committed capture '
      + 'is {message, sleepEnabled, sleepDuration, sleepUnit} (2026-07-25 AU)',
    confidence: 'verified-live',
    attrKeys: ['message', 'sleepEnabled', 'sleepDuration', 'sleepUnit', 'type', '__customInputs__'],
    example: 'research/ai-agents-internal/flow-builder-required-fields.md',
    note: 'committed shape captured 2026-07-25 on AU. UI label -> key: End custom message = message, '
      + 'Reactivate After bot (REQUIRED) = sleepEnabled, Reactivate After value = sleepDuration, unit = sleepUnit ("hours").',
  },
  // Committed capture is `{}` — no fields at all, and the node renders clean. The
  // generated `prompt` key came from a recon read of the panel and does not persist;
  // the marketplace schema confirms this node has no `prompt`. It DOES have an optional
  // `instructions` — absent from the capture only because nothing was authored, which is
  // not evidence the key does not exist.
  conversationai_continue: {
    reason: 'the recon-derived `prompt` key does not persist; the real optional field is `instructions`',
    confidence: 'verified-live',
    attrKeys: ['instructions', 'type', '__customInputs__'],
    example: 'research/ai-agents-internal/flow-builder-required-fields.md',
    note: 'committed shape captured 2026-07-25 on AU is {} (nothing required). `instructions` is an '
      + 'optional textarea per reference/steps/marketplace/conversation-ai.md.',
  },

  // 🔴 The recon panel-read named these `services` / `description`. The assets-endpoint
  // schema gives the real keys, and the OPTIONS ENDPOINT corroborates the first one — it
  // returns `{"conversationai_services": []}`, i.e. the option key IS the attribute key
  // (the same holds for objective's `contactField`). The live findings doc inferred
  // `services`/`description` from UI LABELS only; services_booking was omitted from the
  // rebuild because AU has no commerce services, so there is no committed capture to
  // settle it. Whoever first runs this on an account WITH commerce services should
  // capture the committed shape and promote this to verified-live.
  conversationai_services_booking: {
    reason: 'recon named these services/description; the assets schema + options endpoint say '
      + 'conversationai_services / conversationai_booking_description',
    attrKeys: ['conversationai_services', 'conversationai_booking_description', 'type', '__customInputs__'],
    note: 'NO committed capture — keys come from the marketplace assets schema, with '
      + '`conversationai_services` corroborated by the options-endpoint response key. Unusable on '
      + 'an account with no commerce services.',
  },
  // Committed capture is {assignedEmployeeId} only — the documented `prompt` did NOT
  // persist. Dropping it from attrKeys turns a silent drop into an ATTR_KEY error.
  conversationai_transfer_bot: {
    reason: 'the documented `prompt` key did not persist in the committed capture (2026-07-25 AU)',
    attrKeys: ['assignedEmployeeId', 'type', '__customInputs__'],
    note: 'committed shape captured 2026-07-25 on AU: assignedEmployeeId only. Bot ids come from '
      + 'GET services.leadconnectorhq.com/ai-employees/employees/list?locationId={LOC}.',
  },
};

// How "supplied" is decided per field. `presence` fields are satisfied by ANY value
// including false — live-proven for waitForReply: "waitForReply: false is accepted and
// satisfies the requirement, so it is presence, not truthiness". Everything else must be
// non-empty, because that is exactly what the builder rejects (an empty `description`
// carries the red badge).
const suppliedPresence = (attrs, key) => key in attrs && attrs[key] !== undefined;
const suppliedNonEmpty = (attrs, key) => {
  const v = attrs[key];
  if (v === undefined || v === null) return false;
  if (typeof v === 'string') return v.trim() !== '';
  if (Array.isArray(v)) return v.length > 0;
  return true;
};

// The attested required set. All nine conversationai_* types are listed, including the
// two with nothing required, so this map documents the whole family rather than only the
// failures — an absent entry then unambiguously means "not yet mapped".
export const REQUIRED_FIELDS = {
  conversationai_continue: { fields: {} },    // attested clean: nothing required

  // `objective` is the node's entire purpose and the schema marks it required. The live
  // probe authored it, which is why no builder error was ever seen for it.
  conversationai_objective: {
    fields: {
      objective: { label: 'Objective', hint: 'Author attributes.objective — the prompt describing what to find out.' },
    },
  },

  conversationai_ai_message: {
    fields: {
      // Required per the schema. Never surfaced as a builder error live because the probe
      // always supplied it — absence of an observed error is not evidence of optionality.
      message: { label: 'Message prompt', hint: 'Author attributes.message — the prompt the bot generates from.' },
      waitForReply: {
        label: 'Wait for contact reply',
        presence: true,
        // The schema's own default, matching the captured step-examples.
        default: () => true,
      },
    },
  },
  conversationai_custom_message: {
    fields: {
      message: { label: 'Message', hint: 'Author attributes.message — the literal message to send.' },
      waitForReply: { label: 'Wait for contact reply', presence: true, default: () => true },
    },
  },

  conversationai_ai_splitter: {
    fields: {
      description: {
        label: 'Description',
        // The LLM routes on this text, so the node name is a meaningful fallback — but an
        // unnamed splitter has nothing to fall back TO, and an empty description is what
        // the builder rejects. Defaulting to '' would just re-create the defect.
        default: (node) => node.name,
        hint: 'This is the text the LLM routes on. Author attributes.description, or give the node a `name` to derive it from.',
      },
    },
  },

  conversationai_book_appointment: {
    fields: {
      calendarId: {
        label: 'Select Calendar',
        hint: 'A real calendar id is required and cannot be defaulted. List them with the '
          + 'calendars read tool, then author attributes.calendarId.',
      },
    },
  },

  conversationai_transfer_bot: {
    fields: {
      assignedEmployeeId: {
        label: 'Select Bot to Transfer to',
        hint: 'A real bot id is required and cannot be defaulted. List them with '
          + 'GET services.leadconnectorhq.com/ai-employees/employees/list?locationId={LOC} '
          + '(the response also carries a {value:"keep-same"} sentinel), then author attributes.assignedEmployeeId.',
      },
    },
  },

  conversationai_services_booking: {
    // 🔴 Unusable on a fresh account: the options endpoint returns
    // {"conversationai_services": []} on AU, so there is no id that could satisfy
    // `services` and the node can NEVER go clean. Treat as opt-in per client.
    precondition: 'This node requires a configured commerce service. On AU the options endpoint returned '
      + '{"conversationai_services": []}, meaning no service exists to select and the node can never be '
      + 'satisfied. Confirm the account has commerce services before using it: GET backend.leadconnectorhq.com'
      + '/workflows-marketplace/actions/options/conversationai_services_booking?optionType=default'
      + '&workflowId={WID}&locationId={LOC} (locationId is REQUIRED or it 400s).',
    fields: {
      conversationai_services: {
        label: 'Select Services',
        hint: 'Requires configured commerce services — see the precondition above. NOTE the key is '
          + '`conversationai_services`, not `services`: the options endpoint returns it under that '
          + 'exact name.',
      },
      conversationai_booking_description: {
        label: 'Service Booking Description',
        // The schema's own default for this textarea.
        default: () => 'Get customer to book a service',
      },
    },
  },

  conversationai_end: {
    fields: {
      sleepEnabled: {
        label: 'Reactivate After bot',
        presence: true,
        // ATTESTED, not inferred: the assets-endpoint schema records this checkbox's
        // default as `true`, and the committed capture agrees — {sleepEnabled: true,
        // sleepDuration: 1, sleepUnit: "hours"}. Defaulting to `true` reproduces what the
        // BUILDER itself produces for an untouched node, which is the standard this
        // compiler holds itself to. Author `sleepEnabled: false` to opt out; the schedule
        // halves are then irrelevant and not required.
        default: () => true,
      },
    },
  },
};

// Defaults that only apply once another field takes a particular value. sleepEnabled's
// default of `true` would otherwise trip the coupled check below, since a reactivation
// needs its schedule — so supply the same schedule the capture and the schema show.
const CONDITIONAL_DEFAULTS = {
  conversationai_end: (attrs) => (attrs.sleepEnabled === true
    ? { sleepDuration: attrs.sleepDuration ?? 1, sleepUnit: attrs.sleepUnit ?? 'hours' }
    : {}),
};

// `sleepEnabled: true` is a reactivation SCHEDULE, and the committed capture carried both
// halves of it. Enabling it without a duration/unit persists an incomplete schedule.
function checkCoupledFields(node, attrs) {
  if (node.type !== 'conversationai_end') return;
  if (attrs.sleepEnabled !== true) return;
  const missing = ['sleepDuration', 'sleepUnit'].filter((k) => !suppliedNonEmpty(attrs, k));
  if (missing.length)
    throw new IRError('REQUIRED_FIELD',
      `conversationai_end '${node.ref ?? node.name ?? '?'}' sets sleepEnabled:true without [${missing.join(', ')}]. `
      + `Reactivation is a schedule and needs both halves — the committed capture is `
      + `{sleepEnabled:true, sleepDuration:1, sleepUnit:"hours"}.`);
}

// Fill every defaultable required field and hard-fail the rest. Returns a NEW attrs
// object; never mutates the caller's.
//
// This is the check that makes the difference between "the engine reported success" and
// "the builder can actually publish it". Before it existed, a flow bot could report
// authored:9 / compiled:14 / verify:{pass:14, issues:[]} while the builder showed
// "Resolve 7 Errors".
export function enforceRequiredFields(node, attrs) {
  const spec = REQUIRED_FIELDS[node?.type];
  if (!spec) return attrs;
  const out = { ...attrs };
  const ref = node.ref ?? node.name ?? '?';

  for (const [key, f] of Object.entries(spec.fields)) {
    const supplied = f.presence ? suppliedPresence : suppliedNonEmpty;
    if (supplied(out, key)) continue;

    if (f.default) {
      const value = f.default(node);
      if (supplied({ [key]: value }, key)) { out[key] = value; continue; }
      // The default existed but could not resolve (e.g. description-from-name on an
      // unnamed node). Fall through to the hard error rather than write an empty value,
      // which is the exact state the builder rejects.
    }

    throw new IRError('REQUIRED_FIELD',
      `${node.type} '${ref}' is missing the required attribute '${key}' ("${f.label}"). `
      + `The builder renders this node with a red error badge and the flow CANNOT be published, `
      + `while the build pipeline still reports success — so this must fail at compile time.`
      + (f.hint ? ` ${f.hint}` : '')
      + (spec.precondition ? ` ${spec.precondition}` : ''));
  }

  Object.assign(out, CONDITIONAL_DEFAULTS[node.type]?.(out) ?? {});
  checkCoupledFields(node, out);
  return out;
}

// The required set as plain keys, for the round-trip verify pass (which reads persisted
// attributes back off the wire and has no node object to default from).
export function requiredKeysFor(type) {
  return Object.keys(REQUIRED_FIELDS[type]?.fields ?? {});
}

// Presence semantics, exported so verify applies the SAME rule the compiler did rather
// than re-deriving a second, subtly different notion of "supplied".
export function isSupplied(type, key, attrs) {
  const f = REQUIRED_FIELDS[type]?.fields?.[key];
  if (!f) return true;
  return (f.presence ? suppliedPresence : suppliedNonEmpty)(attrs ?? {}, key);
}
