// Attested required-field enforcement, plus corrections to the generated catalog.
//
// WHY THIS IS NOT IN catalog.data.json
// ------------------------------------
// That file is GENERATED by gen-catalog.mjs, which lives in the ghl-workflow-api-docs
// repo and rewrites it wholesale (`writeFileSync(... JSON.stringify(data))`). A hand-edit
// there is silently lost the next time anyone regenerates and copies it across. This
// overlay is hand-maintained, lives only in the plugin, and is applied on top by
// catalog.mjs — so a regeneration cannot drop it. `catalog-corrections.test.mjs` asserts
// each correction is still NEEDED, so an entry cannot go stale unnoticed.
//
// WHY NOT DRIVE OFF THE CATALOG'S OWN `requiredFields`
// ----------------------------------------------------
// It is marketplace-SCHEMA derived and does not describe the shape GHL actually emits.
// `goto` declares ["placement","targetNodeId"], but its verified-live example carries
// only {targetNodeId, type} and the engine has never emitted `placement`. Enforcing the
// declared set would reject every goto ever built. So the generated field stays advisory
// (query-catalog prints it), and ONLY the entries below — each attested against a
// committed capture or an observed builder error — are enforced.
//
// EVIDENCE: research/ai-agents-internal/flow-builder-required-fields.md, live on AU
// wdzEoUZnXO9tB3PPzcot 2026-07-25/26. Nine conversationai_* node types were built with
// deliberately minimal attributes; the builder reported "Resolve 7 Errors" while the
// engine reported `verify: { pass: 14, issues: [] }`. Supplying the fields below took it
// to "Resolve 1 Errors", and the survivor was conversationai_end — because its DOCUMENTED
// KEY NAMES WERE WRONG (see CATALOG_CORRECTIONS). Fixed and re-verified 2026-07-27: the
// builder's own validation panel now reads "0 Errors — Zero errors, you are all good to go".
//
// ───────────────────────────────────────────────────────────────────────────────────────
// HOW TO RETIRE THIS FILE  (known gap, deliberately left open — not a defect)
// ───────────────────────────────────────────────────────────────────────────────────────
// ROOT CAUSE of the whole class of bug: `catalog/step-examples/` in the docs repo has NO
// captured example for three node types, so gen-catalog.mjs fell back to a recon read of
// the UI panel and recorded WRONG FIELD NAMES for them:
//
//     conversationai_end               ← no capture
//     conversationai_continue          ← no capture
//     conversationai_services_booking  ← no capture
//
// The permanent fix is to capture them, not to keep patching over them. To do that:
//
//   1. Build ONE canary per type with EVERY field populated — not just the required ones.
//      ⚠️ A capture only proves the keys you actually filled. A canary built with minimal
//      attributes would teach gen-catalog that the fields you omitted DO NOT EXIST, which
//      is strictly worse than the current wrong names: the engine would then REJECT valid
//      authoring. This is the single trap to avoid here.
//   2. Export it, anonymise the ids to <uuid-00N> placeholders, and save as
//      `catalog/step-examples/<type>.json` in ghl-workflow-api-docs (match the shape of
//      conversationai_ai_message.json — full node envelope, not just `attributes`).
//   3. Re-run gen-catalog.mjs, copy catalog.data.json across to this repo, and re-run the
//      suite. `required-fields.test.mjs` will FAIL on any correction that has become
//      redundant, naming it — delete those entries from CATALOG_CORRECTIONS.
//
// STATUS as of 2026-07-27:
//   conversationai_continue          — complete shape already known: {instructions}. Easy.
//   conversationai_end               — needs a canary with `message` ALSO set; the
//                                      2026-07-27 canary omitted it, so its export is an
//                                      incomplete capture and must NOT be used as-is.
//   conversationai_services_booking  — BLOCKED. Needs an account with configured commerce
//                                      services; AU's options endpoint returns []. Do this
//                                      opportunistically on a client account that has them.
//
// Until then this overlay is correct and self-policing, so there is no urgency. Behaviour
// is identical either way — retiring it is housekeeping, not a fix.
//
// ── 2026-07-27: the rulebook merge does NOT retire this file. Checked, not assumed. ──────
// `gen-catalog.mjs` now reads GHL's own marketplace schema (`sniffs/assets/`). That schema
// knows all four corrected types, so the obvious expectation was that it would supersede
// them. It does not, and the reasons are worth keeping because they generalise:
//
//   conversationai_end       schema says {message, sleepEnabled} + one DYNAMIC row. The
//                            DYNAMIC row IS sleepDuration/sleepUnit — the schema literally
//                            cannot name them. Correction still load-bearing.
//   conversationai_transfer_bot  schema agrees with the correction ({assignedEmployeeId}).
//   conversationai_continue      schema agrees with the correction ({instructions}).
//   conversationai_services_booking  schema agrees (it is where those keys came from).
//
// Three of four AGREE — and are still not retirable, because a correction carries more than
// key names: it carries `confidence: 'verified-live'`, which is what switches ON the
// compiler's ATTR_KEY guard for that type. Schema data cannot justify that tier (see the
// DYNAMIC problem one line up), so dropping the corrections would silently disarm the guard
// on the very types it was added for. Agreement between an attested capture and the schema
// is corroboration, not redundancy.
//
// `required-fields.test.mjs::every catalog correction is still NEEDED` passes, i.e. the
// generated catalog still disagrees with all four. The retirement path above is unchanged:
// capture the three missing step-examples, and the test will name what to delete.
import { IRError } from './ir.mjs';
import { hasNestedBracketsInExpressions, illegalSmsWords } from './text-rules.mjs';
import CATALOG_DATA from './catalog.data.json' with { type: 'json' };

// GHL ships this list in its own bundle and it rides in the catalog already — 83 words that
// nothing read until now.
const ILLEGAL_SMS_WORDS = CATALOG_DATA?.workflowRules?.vocab?.illegalWordsSms ?? [];

// TRIGGER-side corrections. Same argument as CATALOG_CORRECTIONS below: catalog.data.json is
// regenerated wholesale by gen-catalog.mjs, so a fix written into it is lost on the next regen.
// Applied by catalog.mjs::correctTriggers.
//
// `correctFilterRows` is a MAPPER rather than a replacement array on purpose: a regenerated
// catalog that adds a fifth drawer row still gets corrected instead of silently losing it.
//
// `docNote` is separate from `reason`: `reason` is the engineering justification (probe id,
// error shape) read by whoever maintains this file; `docNote` is user-facing authoring
// guidance rendered into references/capabilities.md by query-catalog.mjs's renderMarkdown.
// capabilities.md is itself GENERATED ("do not hand-edit", enforced by
// query-catalog.test.mjs's sync check) — routing the note through the correction object
// keeps that true instead of hand-editing the committed doc out of sync with its generator.
// RETIRED 2026-08-29 (worked as designed). `resolveMultiSelectType` rewrote
// {__dynamic__:"ValueDataType.MULTI_SELECT"} to 'multiselect' on call_status / validation_error /
// ivr_incoming_call, because extract-trigger-filters.mjs resolved TriggerOperator.* only, so the
// enum reached the catalog as an object, gen-catalog copied it verbatim, and expandFilter copied it
// onto the wire — POST /workflow/{loc}/trigger 500'd on all 7 call_status triggers (F5-16, live
// 2026-08-28). The extractor now resolves every enum in types/, the staleness loop named all three
// entries, and they are gone. call_status keeps a docNote below: that guidance is about how
// dispositions MATCH and was never about the enum.

export const TRIGGER_CORRECTIONS = {
  conv_ai_autonomous_trigger: {
    reason: "GHL's ~2026-08-27 builder update tightened save-time trigger validation: a "
      + "condition row with operator 'eq' is now refused with ruleId trigger-condition-invalid "
      + "(validationType 'value', source 'trigger', severity 'error', ONE ERROR PER ROW), while "
      + "'==' passes. Live A/B 2026-08-27 on the designated test sub-account, workflow "
      + "36bb7c70: identical PUT body, eq -> "
      + '400, == -> 200. The generated filterRows still carry the pre-update `eq` the builder '
      + 'itself wrote, so the catalog capture is right about history and wrong about today. '
      + 'NOTE the blast radius: the validator only runs when triggers are carried IN THE PUT '
      + "BODY, which the engine's own commit never does (proven, arm J) — so stored `eq` "
      + 'triggers block a human clicking Save, not edit_workflow.',
    correctFilterRows: (rows) => rows.map((r) => (r.operator === 'eq' ? { ...r, operator: '==' } : r)),
    docNote: '🔴 Condition rows must carry **`operator: "=="`**. GHL\'s ~2026-08-27 update refuses '
      + '`operator: "eq"` at save time (`ruleId: trigger-condition-invalid`, one error per row) '
      + 'even though the trigger API accepts it and the runtime honours it — so a flow built '
      + 'with `eq` runs correctly and cannot be saved from the builder. The engine emits `==` '
      + 'automatically; a hand-authored complete filter row is passed through untouched, so '
      + 'author `==` yourself if you supply `field`+`operator`+`title`+`type`. '
      + '`catalog/trigger-examples/conv_ai_autonomous_trigger.json` is a pre-update capture and '
      + 'still shows `eq` — it is evidence of what GHL wrote then, not a template to copy.',
  },
  call_status: {
    reason: 'documentation only — the generated filterRows are correct since the extractor resolved '
      + 'ValueDataType.MULTI_SELECT (2026-08-29). Kept because dispositions matching BY NAME is a '
      + 'runtime trap the catalog cannot express: a name absent from Settings never fires.',
    docNote: 'Condition rows on `custom_disposition` / `call_status` are `operator: "contains-any"` with an ARRAY '
      + 'value and `type: "multiselect"` — the drawer\'s own shape. Dispositions are matched BY NAME, so the names '
      + 'must exist in Settings → Phone → Call dispositions or the trigger can never fire.',
  },
};

// Corrections applied over the generated catalog entry, merged in catalog.mjs.
// `reason` is required — an unexplained correction is indistinguishable from a typo.
export const CATALOG_CORRECTIONS = {
  // The capabilities index listed the WIRE type with its wire attrs and nothing said "author the
  // lean name" — pattern-matching from it authored the very door that leaked stage names (T1-1).
  internal_update_opportunity: {
    reason: 'the wire type name routed around the lean builder and the resolver until parseIR canonicalised it '
      + '(2026-08-29); the generated index must steer authors at the lean keys, not the wire ones',
    docNote: 'Author as **`update_opportunity`**: `pipeline`/`stage` NAMES on the build path (the resolver turns '
      + 'them into ids) or `pipelineId`/`stageId` on the edit path, plus `status`, `allowBackward`, `updates[]`. '
      + '`internal_update_opportunity` is accepted as an alias and compiles identically; a NAME that reaches the '
      + 'wire is refused (`UNRESOLVED_NAME`) because GHL stores the word and the step then moves nothing.',
  },
  internal_create_opportunity: {
    reason: 'same wire/lean split as internal_update_opportunity',
    docNote: 'Author as **`create_opportunity`** (lean keys: `pipeline`/`stage` names on the build path, ids on '
      + 'the edit path, plus `name`, `status`, `value`…). `internal_create_opportunity` is accepted as an alias.',
  },
  // 🔴 The generated keys for this node are WRONG. Authoring the documented
  // `reactivate: false` was accepted, persisted as an unknown key, and left the
  // actually-required `sleepEnabled` unset — so the node kept its error badge. The shape
  // below was captured verbatim by filling the node in the builder, clicking Save action
  // then Save workflow, and exporting. Promoted to verified-live on that capture, which
  // also switches on the ATTR_KEY guard (it only fires on verified-live types) so an
  // invented key can no longer pass through here.
  conversationai_end: {
    reason: 'documented keys customMessage/reactivate/duration are wrong; committed capture '
      + 'is {message, sleepEnabled, sleepDuration, sleepUnit} (2026-07-25 AU)',
    confidence: 'verified-live',
    attrKeys: ['message', 'sleepEnabled', 'sleepDuration', 'sleepUnit', 'type', '__customInputs__'],
    example: 'research/ai-agents-internal/flow-builder-required-fields.md',
    note: 'committed shape captured 2026-07-25 on AU. UI label -> key: End custom message = message, '
      + 'Reactivate After bot (REQUIRED) = sleepEnabled, Reactivate After value = sleepDuration, unit = sleepUnit ("hours").',
  },
  // Committed capture is `{}` — no fields at all, and the node renders clean. The
  // generated `prompt` key came from a recon read of the panel and does not persist;
  // the marketplace schema confirms this node has no `prompt`. It DOES have an optional
  // `instructions` — absent from the capture only because nothing was authored, which is
  // not evidence the key does not exist.
  conversationai_continue: {
    reason: 'the recon-derived `prompt` key does not persist; the real optional field is `instructions`',
    confidence: 'verified-live',
    attrKeys: ['instructions', 'type', '__customInputs__'],
    example: 'research/ai-agents-internal/flow-builder-required-fields.md',
    note: 'committed shape captured 2026-07-25 on AU is {} (nothing required). `instructions` is an '
      + 'optional textarea per reference/steps/marketplace/conversation-ai.md.',
  },

  // 🔴 The recon panel-read named these `services` / `description`. The assets-endpoint
  // schema gives the real keys, and the OPTIONS ENDPOINT corroborates the first one — it
  // returns `{"conversationai_services": []}`, i.e. the option key IS the attribute key
  // (the same holds for objective's `contactField`). The live findings doc inferred
  // `services`/`description` from UI LABELS only; services_booking was omitted from the
  // rebuild because AU has no commerce services, so there is no committed capture to
  // settle it. Whoever first runs this on an account WITH commerce services should
  // capture the committed shape and promote this to verified-live.
  conversationai_services_booking: {
    reason: 'recon named these services/description; the assets schema + options endpoint say '
      + 'conversationai_services / conversationai_booking_description',
    attrKeys: ['conversationai_services', 'conversationai_booking_description', 'type', '__customInputs__'],
    note: 'NO committed capture — keys come from the marketplace assets schema, with '
      + '`conversationai_services` corroborated by the options-endpoint response key. Unusable on '
      + 'an account with no commerce services.',
  },
  // Committed capture is {assignedEmployeeId} only — the documented `prompt` did NOT
  // persist. Dropping it from attrKeys turns a silent drop into an ATTR_KEY error.
  conversationai_transfer_bot: {
    reason: 'the documented `prompt` key did not persist in the committed capture (2026-07-25 AU)',
    attrKeys: ['assignedEmployeeId', 'type', '__customInputs__'],
    note: 'committed shape captured 2026-07-25 on AU: assignedEmployeeId only. Bot ids come from '
      + 'GET services.leadconnectorhq.com/ai-employees/employees/list?locationId={LOC}.',
  },

  // The catalog entry for this node is ALREADY confidence:'verified-live' with a 9-key
  // attrKeys list (from catalog/step-examples/conversationai_objective.json), so the
  // ATTR_KEY guard is armed and rejects closingMessage/tags as unknown keys without this
  // patch — which means a blocking objective (proceedIfNotMet:true) cannot compile AT ALL:
  // enforceRequiredFields throws without closingMessage, and checkAttrKeys throws WITH it.
  // Caught live via compile(), not just the unit-level enforceRequiredFields check — see
  // required-fields.test.mjs's 'a blocking objective compiles end to end...' test, which
  // drives the full pipeline.
  //
  // attrKeys REPLACES the generated list (correctSteps spreads the patch), so the original nine
  // keys are carried through verbatim and closingMessage/tags are appended. Evidence for exactly
  // these two, and no others: (1) GHL's action schema dynamicFieldsConfig.customGenerator
  // returns precisely {closingMessage (required:true), tags} the moment proceedIfNotMet is
  // truthy — the schema the builder itself validates against; (2) a UI-built capture on a client
  // account stores precisely those two keys on its one objective with proceedIfNotMet:true, and
  // neither key on its objectives with proceedIfNotMet:false (client identity withheld — this
  // repo is public).
  conversationai_objective: {
    reason: 'proceedIfNotMet is bound directly to the checkbox "Don\'t Proceed to Next Objective '
      + 'If Criteria not Met." (fixtures/action-schema.sample.json input 6) — true means STOP, '
      + 'the opposite of what the name suggests — and checking it makes closingMessage required '
      + '(sibling customGenerator) and reveals optional tags. The generated attrKeys omitted '
      + 'both because the underlying capture was not built with proceedIfNotMet:true; the '
      + 'evidence for adding them is the customGenerator declaring them AND a UI-built capture '
      + 'on a client account storing exactly those two keys only when proceedIfNotMet is true '
      + '(identity withheld). Without this the COUPLED_FIELDS rule below made a blocking '
      + 'objective unauthorable: required without closingMessage, rejected as ATTR_KEY with it.',
    attrKeys: ['objective', 'contactField', 'instructions', 'responseExample', 'skipIfFilled',
      'maxAttempts', 'proceedIfNotMet', 'closingMessage', 'tags', 'type', '__customInputs__'],
    docNote: '🔴 **`proceedIfNotMet` means the OPPOSITE of its name.** It is bound directly to '
      + 'the checkbox "Don\'t Proceed to Next Objective If Criteria not Met.", so `true` = the '
      + 'objective BLOCKS and keeps asking; `false` = carry on to the next objective. For "carry '
      + 'on even if unmet", write `false`. Setting `true` makes `closingMessage` REQUIRED (what '
      + 'the bot says when it gives up) and reveals an optional `tags`; the engine refuses a '
      + 'blocking objective without one.',
  },
};

// How "supplied" is decided per field. `presence` fields are satisfied by ANY value
// including false — live-proven for waitForReply: "waitForReply: false is accepted and
// satisfies the requirement, so it is presence, not truthiness". Everything else must be
// non-empty, because that is exactly what the builder rejects (an empty `description`
// carries the red badge).
const suppliedPresence = (attrs, key) => key in attrs && attrs[key] !== undefined;
const suppliedNonEmpty = (attrs, key) => {
  const v = attrs[key];
  if (v === undefined || v === null) return false;
  if (typeof v === 'string') return v.trim() !== '';
  if (Array.isArray(v)) return v.length > 0;
  return true;
};

// The attested required set. All nine conversationai_* types are listed, including the
// two with nothing required, so this map documents the whole family rather than only the
// failures — an absent entry then unambiguously means "not yet mapped".
export const REQUIRED_FIELDS = {
  conversationai_continue: { fields: {} },    // attested clean: nothing required

  // `objective` is the node's entire purpose and the schema marks it required. The live
  // probe authored it, which is why no builder error was ever seen for it.
  conversationai_objective: {
    fields: {
      objective: { label: 'Objective', hint: 'Author attributes.objective — the prompt describing what to find out.' },
    },
  },

  conversationai_ai_message: {
    fields: {
      // Required per the schema. Never surfaced as a builder error live because the probe
      // always supplied it — absence of an observed error is not evidence of optionality.
      message: { label: 'Message prompt', hint: 'Author attributes.message — the prompt the bot generates from.' },
      waitForReply: {
        label: 'Wait for contact reply',
        presence: true,
        // The schema's own default, matching the captured step-examples.
        default: () => true,
      },
    },
  },
  conversationai_custom_message: {
    fields: {
      message: { label: 'Message', hint: 'Author attributes.message — the literal message to send.' },
      waitForReply: { label: 'Wait for contact reply', presence: true, default: () => true },
    },
  },

  conversationai_ai_splitter: {
    fields: {
      description: {
        label: 'Description',
        // The LLM routes on this text, so the node name is a meaningful fallback — but an
        // unnamed splitter has nothing to fall back TO, and an empty description is what
        // the builder rejects. Defaulting to '' would just re-create the defect.
        default: (node) => node.name,
        hint: 'This is the text the LLM routes on. Author attributes.description, or give the node a `name` to derive it from.',
      },
    },
  },

  conversationai_book_appointment: {
    fields: {
      calendarId: {
        label: 'Select Calendar',
        hint: 'A real calendar id is required and cannot be defaulted. List them with the '
          + 'calendars read tool, then author attributes.calendarId.',
      },
    },
  },

  conversationai_transfer_bot: {
    fields: {
      assignedEmployeeId: {
        label: 'Select Bot to Transfer to',
        hint: 'A real bot id is required and cannot be defaulted. List them with '
          + 'GET services.leadconnectorhq.com/ai-employees/employees/list?locationId={LOC} '
          + '(the response also carries a {value:"keep-same"} sentinel), then author attributes.assignedEmployeeId.',
      },
    },
  },

  conversationai_services_booking: {
    // 🔴 Unusable on a fresh account: the options endpoint returns
    // {"conversationai_services": []} on AU, so there is no id that could satisfy
    // `services` and the node can NEVER go clean. Treat as opt-in per client.
    precondition: 'This node requires a configured commerce service. On AU the options endpoint returned '
      + '{"conversationai_services": []}, meaning no service exists to select and the node can never be '
      + 'satisfied. Confirm the account has commerce services before using it: GET backend.leadconnectorhq.com'
      + '/workflows-marketplace/actions/options/conversationai_services_booking?optionType=default'
      + '&workflowId={WID}&locationId={LOC} (locationId is REQUIRED or it 400s).',
    fields: {
      conversationai_services: {
        label: 'Select Services',
        hint: 'Requires configured commerce services — see the precondition above. NOTE the key is '
          + '`conversationai_services`, not `services`: the options endpoint returns it under that '
          + 'exact name.',
      },
      conversationai_booking_description: {
        label: 'Service Booking Description',
        // The schema's own default for this textarea.
        default: () => 'Get customer to book a service',
      },
    },
  },

  conversationai_end: {
    fields: {
      sleepEnabled: {
        label: 'Reactivate After bot',
        presence: true,
        // ATTESTED, not inferred: the assets-endpoint schema records this checkbox's
        // default as `true`, and the committed capture agrees — {sleepEnabled: true,
        // sleepDuration: 1, sleepUnit: "hours"}. Defaulting to `true` reproduces what the
        // BUILDER itself produces for an untouched node, which is the standard this
        // compiler holds itself to. Author `sleepEnabled: false` to opt out; the schedule
        // halves are then irrelevant and not required.
        default: () => true,
      },
    },
  },
};

// Defaults that only apply once another field takes a particular value. sleepEnabled's
// default of `true` would otherwise trip the coupled check below, since a reactivation
// needs its schedule — so supply the same schedule the capture and the schema show.
// The five wait variants that hang off an appointment-like date and therefore carry the
// "what if that moment has already passed" branch.
const APPOINTMENT_WAIT_TYPES = new Set([
  'appointment', 'service_booking', 'rental_booking', 'attendee_event_date', 'overdue',
]);

const CONDITIONAL_DEFAULTS = {
  conversationai_end: (attrs) => (attrs.sleepEnabled === true
    ? { sleepDuration: attrs.sleepDuration ?? 1, sleepUnit: attrs.sleepUnit ?? 'hours' }
    : {}),

  // GHL's OWN default, not ours. `Wait.setAppointmentStartAfter()` assigns
  // `appointmentConditionType.SKIP_SENDING_OPTION` the moment an appointment wait is created
  // (src/models/conditions/Wait.ts:756), so a UI-built step always carries it. The corpus
  // agrees overwhelmingly: of the stored appointmentCondition values, 94 are 'skip', 6
  // 'specific-step', 2 'next' — 92%, clear of the ≥90% bar uiDefaults requires.
  //
  // Emitting it is what makes an engine-built appointment wait match a UI-built one. Leaving
  // it out is not neutral: the field is optional to GHL, so the step saves either way and the
  // past-time behaviour becomes whatever the backend falls back to, with nothing on screen to
  // say which. 'skip' means skip the outbound send and move on.
  wait: (attrs) => (APPOINTMENT_WAIT_TYPES.has(attrs.type) && attrs.appointmentCondition === undefined
    ? { appointmentCondition: 'skip' }
    : {}),

  // GHL's save validator REQUIRES this key on every add_to_workflow step: a step carrying only
  // {workflow_id, type} is refused with "Input Trigger Params is required", and that refusal
  // blocks EVERY save on the workflow, including edits to unrelated steps. Proven by
  // differential 2026-08-27: the builder PUT body that returned 200 carries
  // input_trigger_params:false on both enrol steps; the one that returned 400 carries neither.
  // It must be a BOOLEAN — the UI drawer writes the string "False", which the post-update
  // validator rejects with "Expected boolean". The type card records it as required:false and
  // present in 100% of the corpus, which is the contradiction that let the engine omit it.
  add_to_workflow: (attrs) => {
    if (attrs.input_trigger_params === undefined) return { input_trigger_params: false };
    // "False" (the exact string the UI drawer writes) is truthy, so coercing here would turn
    // the one value GHL's own validator rejects into one that looks accepted. Refuse instead.
    if (typeof attrs.input_trigger_params !== 'boolean') {
      throw new IRError('ATTR_TYPE',
        `add_to_workflow's 'input_trigger_params' must be a real boolean, not `
        + `${JSON.stringify(attrs.input_trigger_params)} (typeof ${typeof attrs.input_trigger_params}). `
        + `GHL's UI drawer writes the STRING "False" here, which the save validator rejects `
        + `with "Expected boolean" — never coerce a non-boolean value into one.`);
    }
    return {};
  },
};

// Fields that only become required once ANOTHER field takes a particular value. The generated
// catalog cannot express this shape — its enforcement rules are flat per-field guards — so
// conditional couplings live here, each carrying its own evidence.
//
// A rule reads the FINAL attributes (post-default) in `when`, then states EITHER:
//   require: [keys]                  those keys must be non-empty
//   check:   (attrs) => string|null  a problem description, or null when clean
// and carries the severity GHL itself assigns to the same rule:
//   severity 'throw' (default)  GHL says result:'error'    -> refuse the build
//   severity 'warn'             GHL says result:'warning'  -> surface it, build anyway
//
// Matching GHL's tier is the point. Promoting a warning to a throw refuses documents the builder
// opens happily, which breaks the engine's contract in the other direction.
//
// `why` is quoted verbatim in the message: a coupling with no stated reason is indistinguishable
// from a typo.
const hasAttachments = (a) => Boolean(a.attachments?.length || a.urlAttachments?.length);

// The attributes GHL runs isValidHandleBar over, by step type. Only the BRACKET half of that
// check is mirrored (see text-rules.mjs) — the parser half is not portable.
const HANDLEBAR_FIELDS = {
  sms: ['body'],
  messenger: ['body'],
  'instagram-dm': ['body'],
  chatgpt: ['promptText'],
  workflow_ai_generate_image: ['prompt'],
  event_start_date: ['value'],
  add_appointment_booking_ai_bot: ['first_message', 'success_message'],
};

/** One coupling per handlebar-bearing type, generated rather than hand-repeated seven times. */
const handlebarRules = (fields) => [{
  when: (a) => fields.some((f) => hasNestedBracketsInExpressions(a[f])),
  check: (a) => {
    const bad = fields.filter((f) => hasNestedBracketsInExpressions(a[f]));
    return `has a nested bracket inside a handlebar expression in [${bad.join(', ')}]`;
  },
  why: 'A bracket segment containing [ or ] parses fine and then resolves to the WRONG value at '
     + "runtime — ] closes the segment early and [ desynchronises the backend's path splitting. "
     + 'Use {{prefix.[key with spaces].id}}, never a bracket inside a bracket.',
}];

export const COUPLED_FIELDS = {
  // `sleepEnabled: true` is a reactivation SCHEDULE, and the committed capture carried both
  // halves of it. Enabling it without a duration/unit persists an incomplete schedule.
  conversationai_end: [{
    when: (a) => a.sleepEnabled === true,
    require: ['sleepDuration', 'sleepUnit'],
    why: 'Reactivation is a schedule and needs both halves — the committed capture is '
       + '{sleepEnabled:true, sleepDuration:1, sleepUnit:"hours"}.',
  }],

  // 🔴 `proceedIfNotMet` MEANS THE OPPOSITE OF ITS NAME. GHL's own action schema binds it
  // DIRECTLY to a checkbox titled "Don't Proceed to Next Objective If Criteria not Met." —
  // fieldType "checkbox", no inversion layer — so `true` = box checked = the objective BLOCKS
  // and keeps asking, and `false` = carry on. Verified three ways 2026-08-27:
  //   1. the live action schema (fixtures/action-schema.sample.json, conversationai_objective
  //      input 6) carries that exact title against this exact field;
  //   2. its sibling's dynamicFieldsConfig.customGenerator reveals a REQUIRED "Closing Message"
  //      plus an optional "Add a Tag" the moment the field is truthy — the configuration of a
  //      give-up path, not a carry-on path;
  //   3. a real UI-built client workflow (identity withheld — this repo is public) correlates
  //      perfectly: five objectives at false carry no closingMessage, and the one at true
  //      carries a hand-off closing message (a staff member picks the conversation up from
  //      there) plus tags: ''.
  // So a spec author who writes true meaning "carry on" gets a blocking objective that grinds,
  // repeats its ask, and holds the run inside its section.
  conversationai_objective: [{
    when: (a) => a.proceedIfNotMet === true,
    require: ['closingMessage'],
    why: 'proceedIfNotMet:true is the "Don\'t Proceed to Next Objective If Criteria not Met." '
       + 'checkbox — the objective STOPS rather than carrying on, and GHL\'s drawer then makes '
       + '"Closing Message" REQUIRED (its customGenerator returns it with required:true). '
       + 'Without one the step carries a required-field error in the builder. If you meant '
       + '"carry on even when the criteria are not met", the value you want is FALSE.',
  }],

  // THE ONE THE ENGINE ITSELF CREATES. compiler.mjs's email envelope writes `html: a.html ?? ''`
  // on the inline (non-template) path, so an author who supplies a subject and no body gets a
  // step carrying an empty body — which compiles, saves, opens clean, and SENDS BLANK.
  // GHL's own sendEmailActionValidator requires it (`!isTemplateSelected && !cleanHTML(html)`);
  // the generated catalog carried the sibling `subject` rule across and dropped this one.
  // We test non-empty rather than GHL's cleanHTML(), so markup that renders to nothing
  // (`<p></p>`) still passes here — stricter than nothing, not yet as strict as GHL.
  // GHL's spam-word gate applies to `type === 'sms'` ONLY (WorkflowValidator.ts:227) — not to
  // messenger or instagram-dm, despite those sharing the sms body validator. Scoped to match.
  sms: [...handlebarRules(HANDLEBAR_FIELDS.sms), {
    when: (a) => illegalSmsWords(a.body, ILLEGAL_SMS_WORDS).length > 0,
    check: (a) => {
      const hits = illegalSmsWords(a.body, ILLEGAL_SMS_WORDS);
      return `has SMS body word(s) on GHL's blocked list: ${hits.join(', ')}`;
    },
    why: "GHL throws SpamSmsBodyError and ABORTS THE SAVE on these — it is not advisory. The "
       + "list is GHL's and it is blunt (it contains 'pot', 'joint', 'pipe', 'dab'), so an "
       + 'innocent sentence can trip it. Reword the body or the save will fail in GHL anyway.',
  }],

  // ── numeric guards on values that SPEND MONEY ────────────────────────────────────────
  // Both are result:'warning' in GHL, so both warn here. Both exempt a merge tag: a value
  // starting `{{` is resolved at runtime and cannot be judged now — GHL checks for that prefix
  // before parsing, and so do we.
  stripe_one_time_charge: [{
    when: (a) => typeof a.amount === 'string' && a.amount && !a.amount.startsWith('{{'),
    check: (a) => {
      const n = parseFloat(a.amount);
      return Number.isNaN(n) || n <= 0 ? `has a non-positive charge amount: ${JSON.stringify(a.amount)}` : null;
    },
    severity: 'warn',
    why: 'GHL requires a positive amount (other-action-validators.ts:47-59). This step charges a '
       + 'real card, so "abc" or "-5" reaching it is worth stopping to look at.',
  }],
  google_adword: [{
    when: (a) => typeof a.conversion_value === 'string' && a.conversion_value && !a.conversion_value.startsWith('{{'),
    check: (a) => {
      const n = parseFloat(a.conversion_value);
      return Number.isNaN(n) || n <= 0 ? `has a non-positive conversion value: ${JSON.stringify(a.conversion_value)}` : null;
    },
    severity: 'warn',
    why: 'GHL requires a positive conversion value (other-action-validators.ts:102-113). A corrupt '
       + 'value here poisons ad optimisation quietly — the campaign keeps running on bad numbers.',
  }],

  // additional-action-validators.ts:396-403. `op.value === 0` exactly, matching GHL — a string
  // "0" is a different case and GHL does not catch it either.
  math_operation: [{
    when: (a) => Array.isArray(a.operators),
    check: (a) => (a.operators.some((op) => op?.operator === 'div' && op?.value === 0)
      ? 'divides by zero' : null),
    severity: 'warn',
    why: 'A div operator with value 0 fails at runtime, mid-workflow, on whatever contact happens '
       + 'to reach it.',
  }],

  // additional-action-validators.ts:1128-1146. The bound is on the SUM of both lists, which is
  // why neither alone tells you whether the step is valid.
  ivr_connect_call: [{
    when: () => true,
    check: (a) => {
      const total = (a.users?.length ?? 0) + (a.customNumbers?.length ?? 0);
      if (total === 0) return 'rings nobody — it has no users and no custom numbers';
      if (total > 10) return `dials ${total} numbers, over GHL's cap of 10`;
      return null;
    },
    severity: 'warn',
    why: 'GHL requires between 1 and 10 destinations across users + customNumbers combined.',
  }],

  // webhook-validators.ts:104-133. Two content types, two different shapes, both warn.
  custom_webhook: [{
    when: (a) => a.body?.contentType === 'application/json' && typeof a.body?.rawData === 'string' && a.body.rawData.trim(),
    check: (a) => {
      try { JSON.parse(a.body.rawData); return null; }
      catch { return 'declares application/json but its body is not parseable JSON'; }
    },
    severity: 'warn',
    why: 'The remote endpoint 400s at runtime rather than at build time, so this surfaces days '
       + 'later as "the webhook stopped working".',
  }, {
    when: (a) => a.body?.contentType === 'application/x-www-form-urlencoded' && Array.isArray(a.body?.keyValueData),
    check: (a) => (a.body.keyValueData.some((r) => !r?.key?.trim() || r?.value === undefined || r?.value === null)
      ? 'has form-encoded body rows with an empty key or a null value' : null),
    severity: 'warn',
    why: 'GHL checks the body rows as well as the header and parameter rows; the engine warned on '
       + 'the latter two and not on the body, which was inconsistent with its own siblings.',
  }],

  chatgpt: handlebarRules(HANDLEBAR_FIELDS.chatgpt),
  workflow_ai_generate_image: handlebarRules(HANDLEBAR_FIELDS.workflow_ai_generate_image),
  event_start_date: handlebarRules(HANDLEBAR_FIELDS.event_start_date),
  add_appointment_booking_ai_bot: handlebarRules(HANDLEBAR_FIELDS.add_appointment_booking_ai_bot),

  email: [{
    when: (a) => !a.template_id,
    require: ['html'],
    why: 'An inline email carries its body on the step. With no template_id and no html the '
       + 'step sends a blank email — it saves clean and the builder shows no error.',
  }],

  // messenger and instagram-dm have NO enforcement block at all in the generated catalog, and
  // the missing field is the entire payload. Both delegate through to baseSmsValidator, so this
  // mirrors the `sms.body` guard verbatim: `!hasAttachments && !body.trim()`. GHL does not
  // exempt a template there, and neither does this.
  messenger: [...handlebarRules(HANDLEBAR_FIELDS.messenger), {
    when: (a) => !hasAttachments(a),
    require: ['body'],
    why: 'The body IS the message. With no body and no attachment the step sends nothing. '
       + 'Same rule GHL applies to sms — messengerValidator delegates to baseSmsValidator.',
  }],
  'instagram-dm': [...handlebarRules(HANDLEBAR_FIELDS['instagram-dm']), {
    when: (a) => !hasAttachments(a),
    require: ['body'],
    why: 'The body IS the message. With no body and no attachment the step sends nothing. '
       + 'Same rule GHL applies to sms — instagramDmValidator delegates to baseSmsValidator.',
  }],

  wait: [{
    // GHL's OWN rule, never carried across: validateAppointmentWait requires the jump target
    // when the branch is 'specific-step' (wait-validator.ts:288-294, result:'error'). wait has
    // 19 generated throw rules and none covered it.
    when: (a) => a.appointmentCondition === 'specific-step',
    require: ['appointmentSpecificStep'],
    why: 'appointmentCondition:"specific-step" means jump to a named step, so the target is not '
       + 'optional. GHL\'s own validateAppointmentWait requires it.',
  }, {
    // GHL's OWN checkForSpecificDateError (Wait.ts:1473): a STANDARD specific-date wait needs the
    // date AND the hour AND the AM/PM period. The builder paints the step red without them; the
    // API stores it happily and the wait behaves undefined.
    when: (a) => a.type === 'specific_date'
      && !(a.specificDateInputMode === 'dynamic' || a.dynamicSpecificDate !== undefined),
    require: ['specificDate', 'specificTimeHour', 'specificTimePeriod'],
    why: "GHL's checkForSpecificDateError refuses a standard specific-date wait that is missing "
       + 'the date, the hour, or the AM/PM period.',
  }, {
    // Same validator, dynamic branch: the value must be a merge tag, not prose.
    when: (a) => a.type === 'specific_date'
      && (a.specificDateInputMode === 'dynamic' || a.dynamicSpecificDate !== undefined),
    check: (a) => {
      const v = String(a.dynamicSpecificDate ?? '').trim();
      return (!v || !v.startsWith('{{') || !v.endsWith('}}'))
        ? `has dynamicSpecificDate ${JSON.stringify(a.dynamicSpecificDate)}, which is not a merge tag`
        : null;
    },
    why: 'A dynamic specific-date wait reads the date from a merge tag — checkForSpecificDateError '
       + 'requires a value that starts with {{ and ends with }}.',
  }, {
    // checkForDateOffsetError (Wait.ts:1487): before/after with every offset at zero is just "on".
    when: (a) => a.type === 'specific_date'
      && (a.specificDateProceed === 'before' || a.specificDateProceed === 'after'),
    check: (a) => (((a.specificDateOffsetDays ?? 0) === 0 && (a.specificDateOffsetHours ?? 0) === 0
      && (a.specificDateOffsetMinutes ?? 0) === 0)
      ? `proceeds '${a.specificDateProceed}' the date with every offset at 0`
      : null),
    why: "Before/after needs a non-zero offset — otherwise it is just 'on', and GHL's "
       + 'checkForDateOffsetError refuses it.',
  }, {
    // No GHL rule behind this one — stated as ours. Structurally identical to the rule above,
    // on the specific_date variant instead of the appointment variants.
    when: (a) => a.specificDatePassed === 'specific_step',
    require: ['specificDateStep'],
    why: 'specificDatePassed:"specific_step" means jump to a named step once the date has '
       + 'passed, so the target is not optional. Same shape as appointmentSpecificStep.',
  }, {
    // validateTimeWait, wait-validator.ts:151-157, result:'error'. The generated rules cover
    // window.condition === 'when' (start and end) but not the 'exact' branch at all.
    when: (a) => a.type === 'time' && a.window?.condition === 'exact',
    check: (a) => (a.window?.start ? null : 'sets window.condition:"exact" without window.start'),
    why: 'An exact-time window has to say WHICH time. Without a start the backend has nothing '
       + 'to snap the wait to.',
  }, {
    // validateTimeout, wait-validator.ts:368-384. TWO generated rules are wrong about this one
    // and both are left in place because catalog.data.json is regenerated wholesale:
    //
    //   the catalog scopes it to variant `recurring_schedule` at severity 'warn'. GHL scopes it
    //   at the CALL SITE to `convertToMultipath && startAfter` (:97) with no type restriction,
    //   and the inner guard is result:'ERROR'. So the shipped rule fires on a variant that
    //   cannot reach it, at the wrong tier — i.e. never, and wrongly if it did.
    //
    //   the catalog also carries `{field:'type', variant:'recurring_schedule', guard:'!waitType'}`,
    //   which is UNSATISFIABLE: its outer requires type === 'recurring_schedule' while its guard
    //   requires !type. The extractor attached the switch's `default:` branch to the last `case`
    //   label. Its own `support` admits "corpus no sample in variant recurring_schedule".
    //
    // This rule is the correct translation. The dead ones stay until gen-catalog is fixed
    // upstream; they cost nothing but a reader's time, and this comment is that fix.
    when: (a) => Boolean(a.convertToMultipath && a.startAfter),
    check: (a) => (a.startAfter?.value === 0
      ? 'has a branching timeout of 0 — the branch fires immediately instead of waiting' : null),
    why: 'A hybrid wait converts to a multipath on timeout. A timeout of 0 means every contact '
       + 'takes the timeout branch at once, so the wait does nothing and the reply branch is dead.',
  }, {
    // validateConditionWait, wait-validator.ts:195-215, result:'error'. Reached through a
    // `switch` on attributes.type, which the guard-AST extractor does not follow — so the whole
    // sub-validator was dropped. A branch with no segments, or a segment with no conditions,
    // never evaluates true: contacts reach the wait and park there permanently.
    when: (a) => a.type === 'condition',
    check: (a) => {
      const branches = a.condition?.branches ?? [];
      for (let b = 0; b < branches.length; b++) {
        const segments = branches[b].segments ?? [];
        if (!segments.length) return `has condition.branches[${b}] with no segments`;
        for (let g = 0; g < segments.length; g++) {
          if (!(segments[g].conditions ?? []).length)
            return `has condition.branches[${b}].segments[${g}] with no conditions`;
        }
      }
      return null;
    },
    why: 'A conditional wait with an empty branch never becomes true, so every contact that '
       + 'reaches it stops there for good — with nothing anywhere reporting it.',
  }],

  // workflowSplitValidator, additional-action-validators.ts:896-909. result:'warning' in GHL, so
  // it warns here too. compiler.mjs passes author weights through verbatim, so a 30/30 split
  // ships silently and every number measured downstream of it is wrong.
  workflow_split: [{
    when: (a) => a.condition === 'random-split',
    check: (a) => {
      const dist = a.extras?.weightDistribution ?? {};
      const total = Math.round((a.paths ?? []).reduce((n, p) => n + (dist[p?.id] || 0), 0) * 10) / 10;
      return total === 100 ? null : `has random-split weights totalling ${total}, not 100`;
    },
    severity: 'warn',
    why: 'GHL rounds the weights to one decimal and requires exactly 100. Anything else '
       + 'mis-splits traffic, which corrupts the measurement the split exists to produce.',
  }],

  // createUpdateContactValidator / findContactValidator, contact-action-validators.ts:107-113
  // and :170-176. Both result:'warning'.
  create_update_contact: [{
    when: () => true,
    check: (a) => {
      const bad = rowsMissingValue(a);
      return bad.length ? `has field row(s) with no value: ${bad.join(', ')}` : null;
    },
    severity: 'warn',
    why: 'A row with no value writes an empty value over whatever the contact already had.',
  }],
  find_contact: [{
    when: () => true,
    check: (a) => {
      const bad = rowsMissingValue(a);
      return bad.length ? `has field row(s) with no value: ${bad.join(', ')}` : null;
    },
    severity: 'warn',
    why: 'A lookup on an empty value does not identify the contact you meant.',
  }],
};

// GHL's own emptiness test for a contact field row, reproduced verbatim from
// contact-action-validators.ts:107 — an explicit `false` and a `0` are real values, and a date
// row set to 'currentDate' supplies itself.
function rowsMissingValue(attrs) {
  return (attrs.fields ?? [])
    .filter((f) => f && f.value !== false && !f.value && f.date !== 'currentDate' && f.value !== 0)
    .map((f) => f.field ?? '(unnamed)');
}

// A rule states EITHER `require` (these keys must be non-empty) or `check` (returns a problem
// string, or null when clean), and carries the severity GHL itself assigns:
//
//   severity: 'throw'  GHL's validator says result:'error'   → refuse the build
//   severity: 'warn'   GHL's validator says result:'warning' → surface it, build anyway
//
// Matching GHL's tier is the point. Promoting a warning to a throw refuses documents the builder
// would happily open, which breaks the engine's contract in the other direction — and the audit
// already found two rules that had drifted that way.
function checkCoupledFields(node, attrs, ctx) {
  for (const rule of COUPLED_FIELDS[node?.type] ?? []) {
    if (!rule.when(attrs)) continue;
    let problem = null;
    if (rule.require) {
      const missing = rule.require.filter((k) => !suppliedNonEmpty(attrs, k));
      if (missing.length) problem = `is missing [${missing.join(', ')}]`;
    } else if (rule.check) {
      const found = rule.check(attrs);
      if (found) problem = found;
    }
    if (!problem) continue;
    const msg = `${node.type} '${node.ref ?? node.name ?? '?'}' ${problem}. ${rule.why}`;
    if (rule.severity === 'warn') ctx?.warn?.(`COUPLED_SOFT: ${msg}`);
    else throw new IRError('REQUIRED_FIELD', msg);
  }
}

// Fill every defaultable required field and hard-fail the rest. Returns a NEW attrs
// object; never mutates the caller's.
//
// This is the check that makes the difference between "the engine reported success" and
// "the builder can actually publish it". Before it existed, a flow bot could report
// authored:9 / compiled:14 / verify:{pass:14, issues:[]} while the builder showed
// "Resolve 7 Errors".
export function enforceRequiredFields(node, attrs, ctx) {
  const spec = REQUIRED_FIELDS[node?.type];
  // A type can carry CONDITIONAL_DEFAULTS and COUPLED_FIELDS rules without an unconditional
  // REQUIRED_FIELDS entry — `wait` is exactly that: nothing is required of every wait, but an
  // appointment wait takes GHL's own default and a jump branch obliges you to name its target.
  // Returning early on a missing `spec` skipped both, so the tail always runs.
  if (!spec) return finish(node, attrs, ctx);
  const out = { ...attrs };
  const ref = node.ref ?? node.name ?? '?';

  for (const [key, f] of Object.entries(spec.fields)) {
    const supplied = f.presence ? suppliedPresence : suppliedNonEmpty;
    if (supplied(out, key)) continue;

    if (f.default) {
      const value = f.default(node);
      if (supplied({ [key]: value }, key)) { out[key] = value; continue; }
      // The default existed but could not resolve (e.g. description-from-name on an
      // unnamed node). Fall through to the hard error rather than write an empty value,
      // which is the exact state the builder rejects.
    }

    throw new IRError('REQUIRED_FIELD',
      `${node.type} '${ref}' is missing the required attribute '${key}' ("${f.label}"). `
      + `The builder renders this node with a red error badge and the flow CANNOT be published, `
      + `while the build pipeline still reports success — so this must fail at compile time.`
      + (f.hint ? ` ${f.hint}` : '')
      + (spec.precondition ? ` ${spec.precondition}` : ''));
  }

  return finish(node, out, ctx);
}

/** The tail every path shares: apply conditional defaults, then check the couplings.
 *  A type with nothing to add gets its own object back unchanged — callers on the no-spec
 *  path have always relied on that identity, and copying unconditionally would silently
 *  change it for every step type in the catalog. */
function finish(node, out, ctx) {
  const defaults = CONDITIONAL_DEFAULTS[node?.type]?.(out) ?? {};
  const next = Object.keys(defaults).length ? Object.assign({ ...out }, defaults) : out;
  checkCoupledFields(node, next, ctx);
  return next;
}

// The required set as plain keys, for the round-trip verify pass (which reads persisted
// attributes back off the wire and has no node object to default from).
export function requiredKeysFor(type) {
  return Object.keys(REQUIRED_FIELDS[type]?.fields ?? {});
}

// Presence semantics, exported so verify applies the SAME rule the compiler did rather
// than re-deriving a second, subtly different notion of "supplied".
export function isSupplied(type, key, attrs) {
  const f = REQUIRED_FIELDS[type]?.fields?.[key];
  if (!f) return true;
  return (f.presence ? suppliedPresence : suppliedNonEmpty)(attrs ?? {}, key);
}
